### ISSUE TITLE
Unexpectedly behaviour of controllers update

### ISSUE THREAD

**Issue by Sp3zif1sch** [TB-DevAcc/MVSEIQRD_Model#50]
**Describe the bug**
update_params im Controller ersetzt die Werte in self._params durch den letzten Wert des Arrays der Berechnung (hier die Altersgruppe "Rentner") und formt die Werte von (1, 3) in (1,) um.
Das Ergebnis der eigentlichen Simulation, welches update als ```params``` übergeben wird, ist in der Dimension (365, 1, 3).
Ist das Verhalten so beabsichtigt? (Auch das Ergebnis, welches man aus model.run() bekommt, entspricht dem Format des 2ten Bilds)

**To Reproduce**
1. Breakpoint Zeile 318 im Controller
2. Breakpoint Zeile 321 im Controller
3. Lauf einer Simulation im Debug-Mode - Werte sind die aktuellen aus default_values (K=3, J=1, t=365)

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/20173894/154524904-213ebe93-e7e6-4c3c-afa1-3defadc51674.png)
![grafik](https://user-images.githubusercontent.com/20173894/154524993-89676cb7-d1a4-424a-8d8b-7a9007ac46ca.png)

**Comment by Sp3zif1sch** [comment]
Es ist dann ein Bug, wenn die View die Parameter zum Plotten verwendet. Das Model gibt aktuell auch nur die aktualisierten Parameter zurück:
https://github.com/TB-DevAcc/MVSEIQRD_Model/blob/9ae705bef6eaef37431b6448321c8507391e0733/app/model.py#L273-L277

**Comment by TB-DevAcc** [comment]
> Ist das Verhalten so beabsichtigt? (Auch das Ergebnis, welches man aus model.run() bekommt, entspricht dem Format des 2ten Bilds)

Es ist beabsichtigt, dass was wir aus model.run() rausbekommen die gleiche Form hat wie alles was wir manuell in default_values.json eingetragen haben.

**Comment by TB-DevAcc** [comment]
Aber:
> [...]  formt die Werte von (1, 3) in (1,) um.

Es sollte eigentlich die Summe über die letzten beiden Achsen sein, oder? Also der letzte wert der ersten Achse (Letzter Tag) und die Summe der letzten Achsen (Alle Lokalitäten und Altersklassen)? D.h. in controller.py 318 sollte geändert werden und nicht nur den letzten Wert nehmen. 

Bin wie gesagt mit dem ganzen Aufbau mittlerweile auch nicht so zufrieden, würde das gerne nochmal ganz neu machen. Ist aber zeitlich leider nicht drin.

**Comment by TB-DevAcc** [comment]
> Es ist dann ein Bug, wenn die View die Parameter zum Plotten verwendet. 

View verwendet wenn _keine params übergeben_ wird das 1D array der Länge numClasses*t*J*K. Das widerrum enthält ja die Simulationsergebnisse immer komplett und wird separat zu den klassischen controller._params in update_shape_data geupdated. 

Werden _params übergeben_ (wie z.B. falls wir die realen Daten plotten wollen), verwendet View natürlich diese und die sollten dann bereits ein dict in der form {num_classes : (t, J, K)} sein. 

Daher kein bug, oder siehst du das anders?

Übrigens sehr cool, dass du dir das nochmal alles so genau anguckst und eine ordentliche issue geschrieben hast 😄 👍

**Comment by Sp3zif1sch** [comment]
> Es ist beabsichtigt, dass was wir aus model.run() rausbekommen die gleiche Form hat wie alles was wir manuell in default_values.json eingetragen haben.

Oke d.h., wenn wir Werte der Form (J, K) reingeben, wollen wir auch Werte der Form (J, K) rausbekommen.

> Es sollte eigentlich die Summe über die letzten beiden Achsen sein, oder? Also der letzte wert der ersten Achse (Letzter Tag) und die Summe der letzten Achsen (Alle Lokalitäten und Altersklassen)? D.h. in controller.py 318 sollte geändert werden und nicht nur den letzten Wert nehmen.

Aus dem Simulator bekommen wir immer Werte der Form (t, J, K) und wenn wir die gleichen Dimensionen wie bei den Eingabeparametern haben wollen, würde ich eigentlich gar nichts summieren, sondern einfach den Wert an Stelle (-1, J, K) nehmen.

Summieren müssten wir nur, wenn wir die Simulation mit mehreren Landkreisen laufen lassen, aber im Ergebnis nur Deutschland betrachten (das gleiche bei Altersgruppen).

> View verwendet wenn _keine params übergeben_ wird das 1D array der Länge numClasses_t_J*K. Das widerrum enthält ja die Simulationsergebnisse immer komplett und wird separat zu den klassischen controller._params in update_shape_data geupdated.
> 
> Werden _params übergeben_ (wie z.B. falls wir die realen Daten plotten wollen), verwendet View natürlich diese und die sollten dann bereits ein dict in der form {num_classes : (t, J, K)} sein.

Oke, das ist gut! Der Simulator gibt ja eh immer die Form (t, J, K) aus.

> Daher kein bug in view, aber tatsächlich einer für die Umrechnung der Simulationsergebnisse, oder?

Also ```controller.update``` nimmt auf jeden Fall die falsche Dimension als "letzten Wert" oder was meinst du?

> Übrigens sehr cool, dass du dir das nochmal alles so genau anguckst und eine ordentliche issue geschrieben hast 😄 👍

Klar doch 👍

**Comment by TB-DevAcc** [comment]
> Oke d.h., wenn wir Werte der Form (J, K) reingeben, wollen wir auch Werte der Form (J, K) rausbekommen.

Ja.
 
> ```python
> last_params = {k: v[-1] for k, v in params.items()} # -> S = (401, 6)
> ```

Das klingt gut.
 
> ```python
> last_params = {k: np.sum(v[-1], axis=(0)) for k, v in params.items()} # -> S = (6,)
> ```

Das sollte nicht vorkommen oder? Und falls doch, warum tut es das? Ähnliche Frage wie in #54 .

> Also `controller.update` nimmt auf jeden Fall die falsche Dimension als "letzten Wert" oder was meinst du?
 
Ja, genau das was wir oben besprochen haben. -> "sondern einfach den Wert an Stelle (-1, J, K) nehmen"

**Comment by Sp3zif1sch** [comment]
> Das sollte nicht vorkommen oder? Und falls doch, warum tut es das? Ähnliche Frage wie in #54 .

Ne, das kommt aktuell nicht vor, war nur ein Vorschlag, wie der Code dazu aussehen würde. Ich würde aber die Simulation unabhängig davon sowieso nicht mit 401 Landkreisen laufen lassen, da sie dafür ja ca. 10min benötigt.
 
> Ja, genau das was wir oben besprochen haben. -> "sondern einfach den Wert an Stelle (-1, J, K) nehmen"

👍
