### ISSUE TITLE
RKI_COVID19.csv not found; change exception to warning

### ISSUE THREAD

**Issue by TB-DevAcc** [TB-DevAcc/MVSEIQRD_Model#52]
**Description**
Wenn die RKI_COVID19.csv nicht gefunden werden kann (weil z.B. der Download gescheitert ist), sollte das Dashboard trotzdem laufen. Im Presentations-notebook ist dann nur der Abschnitt Data Analysis nicht ausführbar, aber der Hauptteil sollte funktionieren.

**Describe the solution you'd like**
Anstatt eine exception zu werfen, sollte ein Warning ausgegeben werden.

**Describe alternatives you've considered**
Anstatt exception wird die Datei selbständig vom Programm runtergeladen. Hier stellt sich die Frage, von wo? Evlt. direkt vom RKI?

**Comment by Sp3zif1sch** [comment]
https://github.com/TB-DevAcc/MVSEIQRD_Model/blob/084641037e87bb21a9877ae8dcafd0a8657837f1/app/data_handler.py#L22-L23
Habe mir da bereits mal überlegt, den beiden Zeilen im init einfach ein ```if os.path.isfile(<path>):``` davorzuschalten.

**Comment by TB-DevAcc** [comment]
Jop, oder mehr pythonic wäre wahrscheinlich `try ... except`, aber ist beides gut.

Ich habe auch mal den Download link aktualisiert, der sollte jetzt besser funktionieren dann tritt das Problem schonmal nicht mehr so häufig auf.
