### ISSUE TITLE
Germany FuncAnimation 

### ISSUE THREAD

**Issue by Safen-A** [TB-DevAcc/MVSEIQRD_Model#59]
@Sp3zif1sch Max deine Deutschlandkarten Animation funktioniert bei mir lokal ohne probleme, im colab wird sie nicht angezeigt bei einer hohen Anzahl an Tagen, wenn man beispielsweise nur 150 Tage animieren will, dann wird alles angezeigt.

Also lassen wir es dann 150 Tage Animieren oder ganz?

Ich füge die beiden vollständigen Animationen noch als mp4 hinzu

**Comment by TB-DevAcc** [comment]
Würde die vollständige animation sowieso nur als mp4 drin haben. Man kann ja eine if Bedingung rein machen dass die mp4 simuliert/erstellt wird wenn sie nicht im ordner vorhanden ist. So wie wirs bei bouncing balls gemacht haben

**Comment by Sp3zif1sch** [comment]
> @Sp3zif1sch Max deine Deutschlandkarten Animation funktioniert bei mir lokal ohne probleme, im colab wird sie nicht angezeigt bei einer hohen Anzahl an Tagen, wenn man beispielsweise nur 150 Tage animieren will, dann wird alles angezeigt.

Ah oke, lokal hab ichs nicht getestet, da da die Simulation länger dauert, gut zu wissen!

> Ich füge die beiden vollständigen Animationen noch als mp4 hinzu

👍

**Comment by Safen-A** [comment]
> > @Sp3zif1sch Max deine Deutschlandkarten Animation funktioniert bei mir lokal ohne probleme, im colab wird sie nicht angezeigt bei einer hohen Anzahl an Tagen, wenn man beispielsweise nur 150 Tage animieren will, dann wird alles angezeigt.
> 
> Ah oke, lokal hab ichs nicht getestet, da da die Simulation länger dauert, gut zu wissen!
> 
> > Ich füge die beiden vollständigen Animationen noch als mp4 hinzu
> 
> +1

@Sp3zif1sch  Ich hab jetzt deine Simulation eingefügt, die wirft aber derzeit noch einen Fehler.
Weißt du was davon?

` ---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

[<ipython-input-39-877db8f95b51>](https://localhost:8080/#) in <module>()
      1 import time
      2 start = time.time()
--> 3 result = model.run()
      4 end = time.time()
      5 diff = end - start

[/content/MVSEIQRD_Model/app/model.py](https://localhost:8080/#) in run(self)
     263             retParams["D"],
     264         ) = self.simulator.run(params=params, simulation_type=simulation_type)
--> 265         self.controller.update(params=retParams, fill_missing_values=True, reset=False, load_base_data=False)
    266         params = self.controller.get_params()
    267 

TypeError: update() got an unexpected keyword argument 'load_base_data'`

**Comment by Sp3zif1sch** [comment]
> @Sp3zif1sch Ich hab jetzt deine Simulation eingefügt, die wirft aber derzeit noch einen Fehler. Weißt du was davon?

Ja, der ist auch im neuen PR mit behoben, hab ich gerade gemerged. Wenn du ihn schnell lokal beheben willst, dann lösch einfach in Zeile 265 das ```, load_base_data=False```

**Comment by Safen-A** [comment]
Klappt alles ich schließe dieses Issue
